name: Famous Tasks CD - Release & Deployment

on:
  pull_request:
    branches:
      - "release/*"
      - "main"
      - "docker-pull"

jobs:
  release-candidate:
    name: Build Release Candidate
    if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.base_ref, 'release/')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user from PR author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: JDK Configuration
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradlew permission
        run: chmod +x gradlew

      - name: Setup current TAG version
        id: current-tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "OLD_VERSION=$LAST_TAG" >> $GITHUB_ENV

      #Clone repo with other CD logic scripts
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          repository: wcampos-dev/ci-scripts
          path: ci-scripts
          token: ${{ secrets.READ_ONLY_CI_TOKEN }}

#      - name: Release version permission
#        run: chmod +x ./ci-scripts/scripts/release-version.sh

      - name: Execute versioning logic script
        id: version
        run: |
          chmod +x ./ci-scripts/scripts/release-version.sh
          ./ci-scripts/scripts/release-version.sh

      - name: Build Release Candidate Jar artifact
        run: ./gradlew clean build -Pversion=rc-$VERSION

      - name: Create new RC TAG
        run: git tag -a rc-$VERSION -m "Release Candidate rc-$VERSION"

      - name: Push new tag
        run: git push origin rc-$VERSION

  # Baseado no job 'build-main' do ci.yaml original
  production-release:
    name: Build Production Release
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main' || 'refs/heads/docker-pull' || github.base_ref == 'docker-pull'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user from PR author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: JDK Configuration
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradlew permission
        run: chmod +x gradlew

      - name: Setup current TAG version
        id: current-tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "Current Tag $LAST_TAG"
          echo "OLD_VERSION=$LAST_TAG" >> $GITHUB_ENV

      #Clone repo with other CD logic scripts
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          repository: wcampos-dev/ci-scripts
          path: ci-scripts
          token: ${{ secrets.READ_ONLY_CI_TOKEN }}

      - name: Execute versioning logic script
        id: version
        run: |
          chmod +x ./ci-scripts/scripts/release-version.sh
          ./ci-scripts/scripts/release-version.sh

      - name: Build final release artifact
        run: ./gradlew clean build -Pversion=$VERSION

      - name: Publish final release artifact
        uses: actions/upload-artifact@v4
        with:
          name: $VERSION
          path: build/libs/*.jar

      # Docker Imagem - Registry

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Generate current version & latest TAGS
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Render updates notification
      - name: Trigger deploy by Webhook
        # Trigger deploy only for docker-pull (for test. Update to main)
        if: github.ref == 'refs/heads/docker-pull' || github.base_ref == 'docker-pull'
        run: |
          curl -X POST ${{ secrets.DEPLOY_HOOK_URL }}

      - name: Create new Production TAG
        run: |
          echo $VERSION
          git tag -a $VERSION -m "Production Release $VERSION"

      - name: Push new tag
        run: git push origin $VERSION