name: Famous Tasks CI

on:
  push:
    branches:
      - "develop"
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "develop"
      - "main"
      - "release/*"

jobs:
  build-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: JDK Configuration
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradlew permission
        run: chmod +x gradlew
      - name: Build + Test + Coverage
        run: ./gradlew test jacocoTestReport
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=wcampos-dev
            -Dsonar.organization=wcampos-dev
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=build/classes/java/main,build/classes/java/test
            -Dsonar.exclusions=**/src/test/**

  build-release:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: JDK Configuration
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradlew permission
        run: chmod +x gradlew

      # Setup version variable
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          repository: org-ci-scripts
          path: ci-scripts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run version script
        run: ./ci-scripts/scripts/version.sh

      - name: Run Testes
        run: ./gradlew test
      - name: Prepare Release Candidate
        run: ./gradlew clean build -Pversion=RC-${VERSION}

  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: JDK Configuration
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradlew permission
        run: chmod +x gradlew

      # Setup version variable
      - name: Checkout shared scripts
        uses: actions/checkout@v4
        with:
          repository: org-ci-scripts
          path: ci-scripts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run version script
        run: ./ci-scripts/scripts/version.sh

      - name: Build final release
        run: ./gradlew clean build -Pversion=${VERSION}
      - name: Publicar artefatos finais
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/libs/*.jar